name: 'Setup SSH key'
description: 'Setup private key and add host to known hosts'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  private-key:
    description: 'Private key required to access the host'
    required: true
  private-key-name:
    description: 'Name of the key'
    default: 'id_rsa'
    required: false
  known-hosts:
    description: 'Hostname or IP to add to the known hosts file'
    required: false

outputs:
  private-key-path:
    description: 'path to private key'
    value: ${{ steps.setup-output.outputs.private-key-path }}

runs:
  using: 'composite'
  steps: 
    - run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.private-key }}" > ~/.ssh/${{ inputs.private-key-name }}
        chmod 600 ~/.ssh/${{ inputs.private-key-name }}
      shell: bash
    - run: echo "${{ inputs.known-hosts }}" > ~/.ssh/known_hosts
      if: "${{ inputs.inputs.known-hosts != '' }}"
      shell: bash
    - id: setup-output
      run: echo "::set-output name=private-key-path::$(echo ~/.ssh/${{ inputs.private-key-name }})"
      shell: bash
